### ISSUE TITLE
Use ImageIO for wide format support

### ISSUE THREAD

**Issue by FirefoxMetzger** [LaboratoryOpticsBiosciences/bioimageloader#8]
I just bumped into the library, and it looks very exciting 🚀 I particularly like the collections module, which I think has a lot of value; nice work on that!

While looking at the project, I was wondering why you chose to not [depend on ImageIO](https://github.com/imageio/imageio). I think that something like ImageIO would make your life easier compared to calling tiffile, pillow, cv2.imread, ..., explicitly to load the various images. scikit-image, for example, does this internally in skimage.io, and because of this, it can read hundreds of formats including many that are relevant to bioimaging.

Disclaimer: I maintain ImageIO so I may of course be biased. That said, I'm mainly curious about why you chose to not use it (or similar libraries like PIMS) here because I want to know if we are missing something. I always thought of projects like yours as a good use-case for ImageIO, so I'm curious to hear your thoughts to see if we can improve somewhere.

**Comment by sbinnee** [comment]
Hi! Thanks for your interest. I know and love ImageIO too. Reasons that I didn't use ImageIO,
1. It's just that I haven't come across datasets that require formats other than typical image formats (.png, .jpg, .tif)
2. I'd like to keep dependencies as minimal as possible and current image io libraries are actually all dependencies of albumentations and scikit-image.
3. I believe that using low-level libraries is faster and speed is an important factor for bioimageloader (I don't think ImageIO will introduce a big bottleneck, but I still think that it might slow down the process.)

That being said, once bioimageloader got bigger, supported more datasets and formats, I am willing to replace image io funcs with ImageIO. Also I'd like to hear from other users before I make choices.
Thanks for your interest again!

**Comment by FirefoxMetzger** [comment]
>I believe that using low-level libraries is faster and speed is an important factor for bioimageloader (I don't think ImageIO will introduce a big bottleneck, but I still think that it might slow down the process.)

That's an interesting argument. I've been wanting to do a performance comparison of different libraries for a while now to show how big/small the overhead of ImageIO is and to just showcase what various libraries (pillow, openCV, tifffile, gdal, .....) are capable of. I am mainly waiting to get a good grip on what a good/fair comparison would look like. 

Would you have any suggestions how to measure it? There is the obvious "wallclock time of loading a PNG, JPG, GIF, and TIFF", but there are other influencing factors like image size, TIFF flavor (plain, imageJ, MetaMorph, ...), color format, compression level, etc. So I would be curious to hear your thoughts on a comparison strategy.

**Comment by sbinnee** [comment]
I believe that ImageIO will call different backends depending on file extension. I think you can simply use cProfile and filter out backend ops, it may not be simple though?

IO benchmark is certainly my interest. But I think that this is not a place to talk about benchmarking ImageIO. I am willingly to share my thoughts regarding bioimages, if you have an on-going thread and tag me there.

For now I will close this issue.
